name: Upload v0 release
on:
  repository_dispatch:
     types: release_dispatch_v0
jobs:
  On_upload:
    name: Upload integrity and package to release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: v0_dev
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - name: Install dependencies
      run: |
        npm ci
        npm i @actions/core --no-save
    - name: Check version
      id: check_version
      uses: ./.github/actions/check_version
    - name: Build dist/esm
      run: npm run build
    - name: Generate package binary file
      id: generate_binary
      uses: ./.github/actions/generate_binary_file
    - name: Upload integrity artifact
      uses: actions/upload-artifact@v3
      with:
        name: v${{ steps.check_version.outputs.version }}-integrity
        path: ./${{ steps.generate_binary.outputs.integrity }}
    - name: Upload package to release[binaries]
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.WORKFLOW_TOKEN }}
        file: kintone-kintone-ui-component-${{ steps.check_version.outputs.version }}.tgz
        asset_name: kintone-kintone-ui-component-${{ steps.check_version.outputs.version }}.tgz
        tag: v${{ steps.check_version.outputs.version }}
        overwrite: true